---
openapi: 3.0.1
info:
  title: "Crowise Crypto API, the best currency converter \U0001F525"
  version: v1
  description: A REST API that communicates with Buda.com API to provide optimal currency
    conversion paths between different fiat currencies using cryptocurrencies as intermediaries.
paths:
  "/api/v1/convert":
    post:
      summary: Converts currency using the best available path
      tags:
      - Currency Conversion
      description: Converts an amount from one currency to another using cryptocurrencies
        as intermediaries. Returns the best conversion rate and the intermediary used.
      operationId: convertCurrency
      parameters: []
      responses:
        '200':
          description: Same currency conversion
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/conversion_response"
        '400':
          description: Invalid target currency
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/conversion_request"
servers:
- url: https://crowise-crypto.fly.dev
  description: Production server
- url: http://localhost:3000
  description: Development server
components:
  schemas:
    conversion_request:
      type: object
      properties:
        source_currency:
          type: string
          description: Source currency code (CLP, PEN, COP)
        target_currency:
          type: string
          description: Target currency code (CLP, PEN, COP)
        amount:
          type: number
          format: float
          description: Amount in source currency to convert
      required:
      - source_currency
      - target_currency
      - amount
    conversion_response:
      type: object
      properties:
        source_currency:
          type: string
          description: Source currency code
        target_currency:
          type: string
          description: Target currency code
        source_amount:
          type: number
          format: float
          description: Original amount in source currency
        target_amount:
          type: number
          format: float
          description: Converted amount in target currency
        intermediary_currency:
          type: string
          nullable: true
          description: Cryptocurrency used as intermediary
    error:
      type: object
      properties:
        error:
          type: string
